### ISSUE TITLE
Can't install plugin using recommended dokku method

### ISSUE THREAD

**Issue by thngdude** [nonken/dokku-graphicsmagick-plugin#1]
Hi, was glad to see a plugin for graphicsmagick/dokku, but after following the recommended approach to installing the plugin on this page:

https://www.digitalocean.com/community/tutorials/how-to-use-dokku-plugins-to-access-additional-functionality

... my nodejs app is still not recognizing its installation and throws 

Error { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

I can see the plugin folder (dokku-graphicsmagick-plugin) in /var/lib/dokku/plugins

Any idea how to resolve this? Is this a bug? Would appreciate any advice from anyone else who has got this plugin going. Thanks.

**Comment by sveisvei** [comment]
Seams to be no error-messages from install script - but I think the issue is that this plugin doesn't run the install because you dokku/docker container is running 12.04 and apt-get commands are failing.

**Comment by thngdude** [comment]
Yes, it was my version of ubuntu. More recent versions accommodate more packages in the apt-get command. Thanks!
